- name: Install Docker
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        update_cache: yes
        state: present
    - name: Start docker daemon
      systemd:
        name: docker
        state: started

- name: Install docker-compose
  hosts: all
  become: yes
  tasks:
    - name: create docker-compose directory
      file:
        path: /usr/local/lib/docker/cli-plugins
        state: directory
    - name: Get architecture of the remote host
      command: uname -m
      register: remote_arch
    - name: Install docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v5.4.0/docker-compose-linux-{{ remote_arch.stdout }}"
        dest: /usr/local/lib/docker/cli-plugins/docker-compose
        mode: +x